-- USER & AUTHENTICATION TABLES

CREATE TABLE [User] (
  UserID INT PRIMARY KEY IDENTITY(1,1),
  [Name] NVARCHAR(255) NOT NULL,
  Email NVARCHAR(255) UNIQUE NOT NULL,
  PhoneNumber NVARCHAR(20),
  PasswordHash NVARCHAR(255) NOT NULL,
  DateCreated DATETIME2 DEFAULT GETDATE()
);
CREATE INDEX idx_email ON [User](Email);
CREATE INDEX idx_name ON [User]([Name]);

CREATE TABLE CreditCard (
  CreditCardNum NVARCHAR(16) PRIMARY KEY,
  UserID INT NOT NULL,
  CardType NVARCHAR(20) NOT NULL,
  ExpiryDate NVARCHAR(7) NOT NULL,
  CVC NVARCHAR(4) NOT NULL,
  PostalCode NVARCHAR(10) NOT NULL,
  CONSTRAINT FK_CreditCard_User FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE ScenePlusCard (
  SceneCardNumber NVARCHAR(20) PRIMARY KEY,
  PointsBalance INT NOT NULL DEFAULT 0 CHECK (PointsBalance >= 0),
  IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE GiftCard (
  GiftCardNum NVARCHAR(16) PRIMARY KEY,
  UserID INT NOT NULL,
  BalanceAmount DECIMAL(10, 2) NOT NULL CHECK (BalanceAmount >= 0),
  LastUpdated DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_GiftCard_User FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE CineClubMembership (
  MembershipID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT UNIQUE NOT NULL,
  MembershipType NVARCHAR(20) NOT NULL,
  StartDate DATE NOT NULL,
  RenewalDate DATE NOT NULL,
  PaymentFrequency NVARCHAR(20) NOT NULL,
  CONSTRAINT FK_CineClubMembership_User FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CineClubTicket (
  ClubTicketID INT PRIMARY KEY IDENTITY(1,1),
  MembershipID INT NOT NULL,
  TicketType NVARCHAR(30) NOT NULL,
  [Status] NVARCHAR(20) NOT NULL,
  Price DECIMAL(8, 2) NOT NULL,
  IssueDate DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_CineClubTicket_Membership FOREIGN KEY (MembershipID) REFERENCES CineClubMembership(MembershipID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- THEATRE INFRASTRUCTURE TABLES

CREATE TABLE [Complex] (
  ComplexID INT PRIMARY KEY IDENTITY(1,1),
  [Name] NVARCHAR(255) NOT NULL,
  StreetAddress NVARCHAR(255) NOT NULL,
  City NVARCHAR(100) NOT NULL,
  Province NVARCHAR(50) NOT NULL,
  PostalCode NVARCHAR(10) NOT NULL,
  ContactNumber NVARCHAR(20) NOT NULL
);
CREATE INDEX idx_location ON [Complex](City, Province);

CREATE TABLE Hall (
  HallID INT PRIMARY KEY IDENTITY(1,1),
  ComplexID INT NOT NULL,
  HallNumber INT NOT NULL,
  SeatCapacity INT NOT NULL CHECK (SeatCapacity > 0),
  HasVIP BIT DEFAULT 0,
  HasDBox BIT DEFAULT 0,
  CONSTRAINT FK_Hall_Complex FOREIGN KEY (ComplexID) REFERENCES [Complex](ComplexID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT UK_Hall_Number UNIQUE (ComplexID, HallNumber)
);

CREATE TABLE SeatCategory (
  SeatCategoryID INT PRIMARY KEY IDENTITY(1,1),
  CategoryName NVARCHAR(50) UNIQUE NOT NULL,
  BasePriceModifier DECIMAL(4, 2) NOT NULL,
  IsAccessible BIT DEFAULT 0
);

CREATE TABLE Seat (
  SeatID INT PRIMARY KEY IDENTITY(1,1),
  HallID INT NOT NULL,
  SeatRow NVARCHAR(5) NOT NULL,
  SeatColumn INT NOT NULL,
  SeatCategoryID INT NOT NULL,
  CONSTRAINT FK_Seat_Hall FOREIGN KEY (HallID) REFERENCES Hall(HallID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_Seat_Category FOREIGN KEY (SeatCategoryID) REFERENCES SeatCategory(SeatCategoryID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT UK_Seat_Location UNIQUE (HallID, SeatRow, SeatColumn)
);

-- MOVIE & CONTENT TABLES

CREATE TABLE Movie (
  MovieID INT PRIMARY KEY IDENTITY(1,1),
  Title NVARCHAR(255) NOT NULL,
  Synopsis NVARCHAR(MAX),
  IMDBRating DECIMAL(3, 1),
  [Language] NVARCHAR(10) NOT NULL,
  ReleaseDate DATE,
  Duration INT NOT NULL CHECK (Duration > 0),
  PG_Rating NVARCHAR(10) NOT NULL
);

CREATE TABLE [Genre] (
  GenreID INT PRIMARY KEY IDENTITY(1,1),
  GenreName NVARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE MovieGenre (
  MovieID INT NOT NULL,
  GenreID INT NOT NULL,
  PRIMARY KEY (MovieID, GenreID),
  CONSTRAINT FK_MovieGenre_Movie FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_MovieGenre_Genre FOREIGN KEY (GenreID) REFERENCES [Genre](GenreID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CastMember (
  CastID INT PRIMARY KEY IDENTITY(1,1),
  [Name] NVARCHAR(255) NOT NULL
);

CREATE TABLE MovieCast (
  MovieID INT NOT NULL,
  CastID INT NOT NULL,
  RoleType NVARCHAR(50) NOT NULL,
  PRIMARY KEY (MovieID, CastID),
  CONSTRAINT FK_MovieCast_Movie FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_MovieCast_Cast FOREIGN KEY (CastID) REFERENCES CastMember(CastID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MovieMedia (
  MediaID INT PRIMARY KEY IDENTITY(1,1),
  MovieID INT NOT NULL,
  MediaType NVARCHAR(30) NOT NULL,
  MediaURL NVARCHAR(500),
  MediaFile NVARCHAR(255),
  UploadDate DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_MovieMedia_Movie FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- SCREENING & PROGRAMMING TABLES

CREATE TABLE Screening (
  ScreeningID INT PRIMARY KEY IDENTITY(1,1),
  HallID INT NOT NULL,
  MovieID INT NOT NULL,
  ScreeningDate DATE NOT NULL,
  StartTime TIME NOT NULL,
  EndTime TIME NOT NULL,
  Is3D BIT DEFAULT 0,
  CONSTRAINT FK_Screening_Hall FOREIGN KEY (HallID) REFERENCES Hall(HallID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_Screening_Movie FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT CHK_Screening_Times CHECK (StartTime < EndTime)
);
CREATE INDEX idx_screening_schedule ON Screening(HallID, ScreeningDate, StartTime);

CREATE TABLE CurrentlyPlaying (
  ComplexID INT NOT NULL,
  MovieID INT NOT NULL,
  IsFeatured BIT DEFAULT 0,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  PRIMARY KEY (ComplexID, MovieID),
  CONSTRAINT FK_CurrentlyPlaying_Complex FOREIGN KEY (ComplexID) REFERENCES [Complex](ComplexID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_CurrentlyPlaying_Movie FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT CHK_Playing_Dates CHECK (EndDate >= StartDate)
);

-- BOOKING & RESERVATION TABLES

CREATE TABLE SeatLock (
  LockID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL,
  SeatID INT NOT NULL,
  ScreeningID INT NOT NULL,
  LockStartTime DATETIME2 DEFAULT GETDATE(),
  LockExpiryTime DATETIME2 NOT NULL,
  [Status] NVARCHAR(20) NOT NULL,
  CONSTRAINT FK_SeatLock_User FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_SeatLock_Seat FOREIGN KEY (SeatID) REFERENCES Seat(SeatID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_SeatLock_Screening FOREIGN KEY (ScreeningID) REFERENCES Screening(ScreeningID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT CHK_Lock_Expiry CHECK (LockExpiryTime > LockStartTime)
);
CREATE INDEX idx_seat_screening ON SeatLock(SeatID, ScreeningID);

CREATE TABLE Booking (
  BookingID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL,
  ScreeningID INT NOT NULL,
  BookingTime DATETIME2 DEFAULT GETDATE(),
  [Status] NVARCHAR(20) NOT NULL,
  TotalPrice DECIMAL(10, 2) NOT NULL CHECK (TotalPrice >= 0),
  CONSTRAINT FK_Booking_User FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_Booking_Screening FOREIGN KEY (ScreeningID) REFERENCES Screening(ScreeningID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX idx_user_booking ON Booking(UserID, ScreeningID);

CREATE TABLE seatBooking (
  seatBookingID INT PRIMARY KEY IDENTITY(1,1),
  BookingID INT NOT NULL,
  SeatID INT NOT NULL,
  ScreeningID INT NOT NULL,
  SeatCost DECIMAL(8, 2) NOT NULL CHECK (SeatCost >= 0),
  SeatBookingStatus NVARCHAR(20) NOT NULL,
  CONSTRAINT FK_SeatBooking_Booking FOREIGN KEY (BookingID) REFERENCES Booking(BookingID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_SeatBooking_Seat FOREIGN KEY (SeatID) REFERENCES Seat(SeatID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_SeatBooking_Screening FOREIGN KEY (ScreeningID) REFERENCES Screening(ScreeningID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX idx_booking_seat ON seatBooking(BookingID, SeatID);

-- CONCESSIONS TABLES

CREATE TABLE Snack (
  SnackID INT PRIMARY KEY IDENTITY(1,1),
  SnackName NVARCHAR(100) NOT NULL,
  Category NVARCHAR(50) NOT NULL,
  Price DECIMAL(6, 2) NOT NULL CHECK (Price > 0),
  IsCombo BIT DEFAULT 0,
  IsAvailable BIT DEFAULT 1
);

CREATE TABLE SnackOrder (
  SnackOrderID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL,
  ComplexID INT NOT NULL,
  OrderTime DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_SnackOrder_User FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_SnackOrder_Complex FOREIGN KEY (ComplexID) REFERENCES [Complex](ComplexID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE SnackOrderItem (
  SnackOrderItemID INT PRIMARY KEY IDENTITY(1,1),
  SnackOrderID INT NOT NULL,
  SnackID INT NOT NULL,
  Quantity INT NOT NULL CHECK (Quantity > 0),
  PricePerUnit DECIMAL(6, 2) NOT NULL CHECK (PricePerUnit > 0),
  Subtotal DECIMAL(8, 2) NOT NULL CHECK (Subtotal > 0),
  CONSTRAINT FK_SnackOrderItem_Order FOREIGN KEY (SnackOrderID) REFERENCES SnackOrder(SnackOrderID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_SnackOrderItem_Snack FOREIGN KEY (SnackID) REFERENCES Snack(SnackID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- PAYMENT & TRANSACTION TABLES

CREATE TABLE [Payment] (
  PaymentID INT PRIMARY KEY IDENTITY(1,1),
  BookingID INT,
  SnackOrderID INT,
  PaymentMethod NVARCHAR(50) NOT NULL,
  StartTime DATETIME2 DEFAULT GETDATE(),
  EndTime DATETIME2,
  AmountPaid DECIMAL(10, 2) NOT NULL CHECK (AmountPaid >= 0),
  Taxes DECIMAL(8, 2) NOT NULL CHECK (Taxes >= 0),
  TicketSubtotal DECIMAL(10, 2),
  SnackSubtotal DECIMAL(10, 2),
  TotalPaid DECIMAL(10, 2) NOT NULL CHECK (TotalPaid >= 0),
  CONSTRAINT CHK_Payment_Link CHECK (BookingID IS NOT NULL OR SnackOrderID IS NOT NULL),
  CONSTRAINT CHK_Total_Paid CHECK (TotalPaid = ISNULL(TicketSubtotal, 0) + ISNULL(SnackSubtotal, 0) + Taxes),
  CONSTRAINT FK_Payment_Booking FOREIGN KEY (BookingID) REFERENCES Booking(BookingID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_Payment_SnackOrder FOREIGN KEY (SnackOrderID) REFERENCES SnackOrder(SnackOrderID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX idx_payment_booking ON [Payment](BookingID);
CREATE INDEX idx_payment_snack ON [Payment](SnackOrderID);

CREATE TABLE CreditCardPayment (
  PaymentID INT PRIMARY KEY,
  CreditCardNum NVARCHAR(16) NOT NULL,
  AmountCharged DECIMAL(10, 2) NOT NULL CHECK (AmountCharged > 0),
  CONSTRAINT FK_CreditCardPayment_Payment FOREIGN KEY (PaymentID) REFERENCES [Payment](PaymentID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_CreditCardPayment_Card FOREIGN KEY (CreditCardNum) REFERENCES CreditCard(CreditCardNum) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE GiftCardPayment (
  GcTrxnID INT PRIMARY KEY IDENTITY(1,1),
  PaymentID INT NOT NULL,
  GiftCardNum NVARCHAR(16) NOT NULL,
  AmountDeducted DECIMAL(10, 2) NOT NULL CHECK (AmountDeducted > 0),
  TransactionTime DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_GiftCardPayment_Payment FOREIGN KEY (PaymentID) REFERENCES [Payment](PaymentID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_GiftCardPayment_Card FOREIGN KEY (GiftCardNum) REFERENCES GiftCard(GiftCardNum) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE SceneRedemption (
  RedemptionID INT PRIMARY KEY IDENTITY(1,1),
  PaymentID INT NOT NULL,
  SceneCardNumber NVARCHAR(20) NOT NULL,
  PointsUsed INT NOT NULL CHECK (PointsUsed > 0),
  AmountCovered DECIMAL(10, 2) NOT NULL CHECK (AmountCovered > 0),
  RedemptionTime DATETIME2 DEFAULT GETDATE(),
  CONSTRAINT FK_SceneRedemption_Payment FOREIGN KEY (PaymentID) REFERENCES [Payment](PaymentID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_SceneRedemption_Card FOREIGN KEY (SceneCardNumber) REFERENCES ScenePlusCard(SceneCardNumber) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Receipt (
  ReceiptID INT PRIMARY KEY IDENTITY(1,1),
  PaymentID INT UNIQUE NOT NULL,
  UserID INT NOT NULL,
  BookingID INT,
  SnackOrderID INT,
  PurchaseDateTime DATETIME2 DEFAULT GETDATE(),
  Total DECIMAL(10, 2) NOT NULL CHECK (Total >= 0),
  CONSTRAINT FK_Receipt_Payment FOREIGN KEY (PaymentID) REFERENCES [Payment](PaymentID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_Receipt_User FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_Receipt_Booking FOREIGN KEY (BookingID) REFERENCES Booking(BookingID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_Receipt_SnackOrder FOREIGN KEY (SnackOrderID) REFERENCES SnackOrder(SnackOrderID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- PERFORMANCE INDEXES

CREATE INDEX idx_user_email ON [User](Email);
CREATE INDEX idx_booking_user_date ON Booking(UserID, BookingTime);
CREATE INDEX idx_seat_booking_status ON seatBooking(SeatBookingStatus);
CREATE INDEX idx_seat_lock_expiry ON SeatLock(LockExpiryTime);
CREATE INDEX idx_movie_title ON Movie(Title);
CREATE INDEX idx_movie_genre ON MovieGenre(GenreID);
CREATE INDEX idx_screening_movie ON Screening(MovieID);
CREATE INDEX idx_payment_method ON [Payment](PaymentMethod);
CREATE INDEX idx_payment_time ON [Payment](StartTime);
CREATE INDEX idx_snack_order_user ON SnackOrder(UserID);
CREATE INDEX idx_snack_order_complex ON SnackOrder(ComplexID);